import { useState } from 'react';
import { BookOpen, ChevronRight, Search } from 'lucide-react';
import { useListStandards } from '@workspace/api-client-react';
import { EmptyState, ErrorState, LoadingRows, titleCase } from '@/components/ui-pieces';

export function StandardsPage() {
  const [search, setSearch] = useState('');
  const query = useListStandards({ search: search || undefined });
  const standards = query.data ?? [];
  return <div className="animate-rise-in space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="eyebrow">Australian references</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Standards library</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">A quick field reference for the requirements behind your findings.</p></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><BookOpen size={15} className="text-primary" /> {query.isLoading ? 'Updating…' : `${standards.length} references`}</div></div>
    <div className="flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} data-testid="input-search-standards" placeholder="Search by code, title, clause or requirement" className="field-input pl-9" /></label></div>
    {query.isLoading ? <LoadingRows count={5} /> : query.isError ? <ErrorState retry={() => query.refetch()} /> : standards.length ? <div className="grid gap-3">{standards.map((standard) => <StandardCard key={standard.id} standard={standard} />)}</div> : <EmptyState title="No references found" detail="Try a code such as AS 1684 or a topic such as termite management." />}
  </div>;
}
function StandardCard({ standard }: { standard: import('@workspace/api-client-react').StandardReference }) { return <article data-testid={`card-standard-${standard.id}`} className="group rounded-lg border border-card-border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-md"><div className="flex flex-col justify-between gap-4 md:flex-row"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-primary/10 px-2 py-1 font-mono text-xs font-medium text-primary">{standard.code}</span><span className="text-[10px] uppercase tracking-wider text-muted-foreground">{titleCase(standard.category)}</span></div><h2 className="mt-3 text-base font-semibold">{standard.title}</h2><p className="mt-1 text-xs text-muted-foreground">Clause {standard.clause}</p></div><ChevronRight size={18} className="shrink-0 text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:text-primary" /></div><div className="mt-4 grid gap-4 border-t border-border/70 pt-4 md:grid-cols-2"><div><div className="eyebrow">Requirement</div><p className="mt-1 text-sm leading-relaxed text-foreground/80">{standard.requirement}</p></div><div><div className="eyebrow">Tolerance / benchmark</div><p className="mt-1 text-sm leading-relaxed text-foreground/80">{standard.tolerance}</p></div></div><div className="mt-4 flex items-center gap-1.5 text-[11px] text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-primary" /> Source: {standard.source}</div></article>; }